/**
 * @file binocan.c
 *
 * @brief This source file was generated by cantools version 40.2.1 Thu Jul 17 13:46:18 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "binocan.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int binocan_extra_chargecooling_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_extra_chargecooling_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bitmask, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->charge_coolant_temp_in, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->charge_coolant_temp_out, 0u, 0xffu);

    return (8);
}

int binocan_extra_chargecooling_metrics_unpack(
    struct binocan_extra_chargecooling_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bitmask = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->charge_coolant_temp_in = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->charge_coolant_temp_out = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_extra_chargecooling_metrics_init(struct binocan_extra_chargecooling_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_extra_chargecooling_metrics_t));

    return 0;
}

uint8_t binocan_extra_chargecooling_metrics_bitmask_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_extra_chargecooling_metrics_bitmask_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_extra_chargecooling_metrics_bitmask_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_extra_chargecooling_metrics_charge_coolant_temp_in_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_extra_chargecooling_metrics_charge_coolant_temp_in_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_extra_chargecooling_metrics_charge_coolant_temp_in_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_extra_chargecooling_metrics_charge_coolant_temp_out_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_extra_chargecooling_metrics_charge_coolant_temp_out_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_extra_chargecooling_metrics_charge_coolant_temp_out_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_base_telltales_pack(
    uint8_t *dst_p,
    const struct binocan_base_telltales_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->abs_tt, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->airbag_tt, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->cel_tt, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->high_beams_tt, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->low_brake_fluid_tt, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->low_coolant_tt, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->low_fuel_tt, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->low_oil_pressure_tt, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->lv_system_tt, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->over_temperature_tt, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->parking_brake_tt, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->turn_indicators_tt, 3u, 0x08u);

    return (8);
}

int binocan_base_telltales_unpack(
    struct binocan_base_telltales_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->abs_tt = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->airbag_tt = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->cel_tt = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->high_beams_tt = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->low_brake_fluid_tt = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->low_coolant_tt = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->low_fuel_tt = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->low_oil_pressure_tt = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->lv_system_tt = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->over_temperature_tt = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->parking_brake_tt = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->turn_indicators_tt = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    return (0);
}

int binocan_base_telltales_init(struct binocan_base_telltales_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_base_telltales_t));

    return 0;
}

uint8_t binocan_base_telltales_abs_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_abs_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_abs_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_airbag_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_airbag_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_airbag_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_cel_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_cel_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_cel_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_high_beams_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_high_beams_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_high_beams_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_low_brake_fluid_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_low_brake_fluid_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_low_brake_fluid_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_low_coolant_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_low_coolant_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_low_coolant_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_low_fuel_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_low_fuel_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_low_fuel_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_low_oil_pressure_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_low_oil_pressure_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_low_oil_pressure_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_lv_system_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_lv_system_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_lv_system_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_over_temperature_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_over_temperature_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_over_temperature_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_parking_brake_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_parking_brake_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_parking_brake_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_telltales_turn_indicators_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_telltales_turn_indicators_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_telltales_turn_indicators_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int binocan_extra_oil_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_extra_oil_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bitmask, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->oil_pressure, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->oil_temperature, 0u, 0xffu);

    return (8);
}

int binocan_extra_oil_metrics_unpack(
    struct binocan_extra_oil_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bitmask = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->oil_pressure = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->oil_temperature = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_extra_oil_metrics_init(struct binocan_extra_oil_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_extra_oil_metrics_t));

    return 0;
}

uint8_t binocan_extra_oil_metrics_bitmask_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_extra_oil_metrics_bitmask_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_extra_oil_metrics_bitmask_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_extra_oil_metrics_oil_pressure_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double binocan_extra_oil_metrics_oil_pressure_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool binocan_extra_oil_metrics_oil_pressure_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_extra_oil_metrics_oil_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_extra_oil_metrics_oil_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_extra_oil_metrics_oil_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_base_slow_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_base_slow_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->coolant_temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->fuel_level, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->lv_voltage, 0u, 0xffu);

    return (8);
}

int binocan_base_slow_metrics_unpack(
    struct binocan_base_slow_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->coolant_temp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fuel_level = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->lv_voltage = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_base_slow_metrics_init(struct binocan_base_slow_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_base_slow_metrics_t));

    return 0;
}

uint8_t binocan_base_slow_metrics_coolant_temp_encode(double value)
{
    return (uint8_t)((value - 70.0) / 0.4);
}

double binocan_base_slow_metrics_coolant_temp_decode(uint8_t value)
{
    return (((double)value * 0.4) + 70.0);
}

bool binocan_base_slow_metrics_coolant_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_base_slow_metrics_fuel_level_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double binocan_base_slow_metrics_fuel_level_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool binocan_base_slow_metrics_fuel_level_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_base_slow_metrics_lv_voltage_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double binocan_base_slow_metrics_lv_voltage_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool binocan_base_slow_metrics_lv_voltage_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_base_vehicle_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_base_vehicle_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->speed, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->speed, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->ignition_st, 0u, 0x01u);

    return (8);
}

int binocan_base_vehicle_metrics_unpack(
    struct binocan_base_vehicle_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->speed = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->speed |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->ignition_st = unpack_right_shift_u8(src_p[4], 0u, 0x01u);

    return (0);
}

int binocan_base_vehicle_metrics_init(struct binocan_base_vehicle_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_base_vehicle_metrics_t));

    return 0;
}

uint16_t binocan_base_vehicle_metrics_rpm_encode(double value)
{
    return (uint16_t)(value / 0.14);
}

double binocan_base_vehicle_metrics_rpm_decode(uint16_t value)
{
    return ((double)value * 0.14);
}

bool binocan_base_vehicle_metrics_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t binocan_base_vehicle_metrics_speed_encode(double value)
{
    return (uint16_t)(value / 0.04);
}

double binocan_base_vehicle_metrics_speed_decode(uint16_t value)
{
    return ((double)value * 0.04);
}

bool binocan_base_vehicle_metrics_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_base_vehicle_metrics_ignition_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_base_vehicle_metrics_ignition_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_base_vehicle_metrics_ignition_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
