/**
 * @file binocan.h
 *
 * @brief This header file was generated by cantools version 40.2.1 Mon Aug  4 12:40:21 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BINOCAN_H
#define BINOCAN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_FRAME_ID (0x201u)
#define BINOCAN_BASE_ACTIVE_HI_LO_FRAME_ID (0x101u)
#define BINOCAN_EXTRA_OIL_METRICS_FRAME_ID (0x200u)
#define BINOCAN_BASE_SLOW_METRICS_FRAME_ID (0x110u)
#define BINOCAN_BASE_FAST_METRICS_FRAME_ID (0x100u)

/* Frame lengths in bytes. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_LENGTH (8u)
#define BINOCAN_BASE_ACTIVE_HI_LO_LENGTH (8u)
#define BINOCAN_EXTRA_OIL_METRICS_LENGTH (8u)
#define BINOCAN_BASE_SLOW_METRICS_LENGTH (8u)
#define BINOCAN_BASE_FAST_METRICS_LENGTH (8u)

/* Extended or standard frame types. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_IS_EXTENDED (0)
#define BINOCAN_BASE_ACTIVE_HI_LO_IS_EXTENDED (0)
#define BINOCAN_EXTRA_OIL_METRICS_IS_EXTENDED (0)
#define BINOCAN_BASE_SLOW_METRICS_IS_EXTENDED (0)
#define BINOCAN_BASE_FAST_METRICS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define BINOCAN_BASE_ACTIVE_HI_LO_IGNITION_AH_ST_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_IGNITION_AH_ST_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_HI_BEAMS_AH_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_HI_BEAMS_AH_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_ALTERNATOR_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_ALTERNATOR_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_BRAKE_LOW_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_BRAKE_LOW_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_PARKING_BRAKE_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_PARKING_BRAKE_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_OIL_PRESSURE_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_OIL_PRESSURE_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_AIRBAG_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_AIRBAG_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_CEL_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_CEL_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_RIGHT_TURN_AH_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_RIGHT_TURN_AH_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_LEFT_TURN_AH_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_LEFT_TURN_AH_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_ABS_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_ABS_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_DOOR_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_DOOR_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_COOLANT_LOW_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_COOLANT_LOW_AL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_BUTTON_AL_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_BUTTON_AL_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_B07_AH_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_B07_AH_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_BACKLIGHT_AH_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_BACKLIGHT_AH_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_OVER_TEMPERATURE_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_OVER_TEMPERATURE_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_ACTIVE_HI_LO_FUEL_LOW_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_ACTIVE_HI_LO_FUEL_LOW_TT_ON_CHOICE (1u)

/* Frame Names. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_NAME "extra_chargecooling_metrics"
#define BINOCAN_BASE_ACTIVE_HI_LO_NAME "base_active_hi_lo"
#define BINOCAN_EXTRA_OIL_METRICS_NAME "extra_oil_metrics"
#define BINOCAN_BASE_SLOW_METRICS_NAME "base_slow_metrics"
#define BINOCAN_BASE_FAST_METRICS_NAME "base_fast_metrics"

/* Signal Names. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_BITMASK_NAME "bitmask"
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_CHARGE_COOLANT_TEMP_IN_NAME "charge_coolant_temp_in"
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_CHARGE_COOLANT_TEMP_OUT_NAME "charge_coolant_temp_out"
#define BINOCAN_BASE_ACTIVE_HI_LO_IGNITION_AH_ST_NAME "ignition_AH_ST"
#define BINOCAN_BASE_ACTIVE_HI_LO_HI_BEAMS_AH_TT_NAME "hi_beams_AH_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_ALTERNATOR_AL_TT_NAME "alternator_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_BRAKE_LOW_AL_TT_NAME "brake_low_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_PARKING_BRAKE_AL_TT_NAME "parking_brake_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_OIL_PRESSURE_AL_TT_NAME "oil_pressure_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_AIRBAG_AL_TT_NAME "airbag_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_CEL_AL_TT_NAME "CEL_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_RIGHT_TURN_AH_TT_NAME "right_turn_AH_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_LEFT_TURN_AH_TT_NAME "left_turn_AH_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_ABS_AL_TT_NAME "abs_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_DOOR_AL_TT_NAME "door_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_COOLANT_LOW_AL_TT_NAME "coolant_low_AL_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_BUTTON_AL_NAME "button_AL"
#define BINOCAN_BASE_ACTIVE_HI_LO_B07_AH_NAME "B07_AH"
#define BINOCAN_BASE_ACTIVE_HI_LO_BACKLIGHT_AH_NAME "backlight_AH"
#define BINOCAN_BASE_ACTIVE_HI_LO_OVER_TEMPERATURE_TT_NAME "over_temperature_TT"
#define BINOCAN_BASE_ACTIVE_HI_LO_FUEL_LOW_TT_NAME "fuel_low_TT"
#define BINOCAN_EXTRA_OIL_METRICS_BITMASK_NAME "bitmask"
#define BINOCAN_EXTRA_OIL_METRICS_OIL_PRESSURE_NAME "oil_pressure"
#define BINOCAN_EXTRA_OIL_METRICS_OIL_TEMPERATURE_NAME "oil_temperature"
#define BINOCAN_BASE_SLOW_METRICS_COOLANT_TEMP_NAME "coolant_temp"
#define BINOCAN_BASE_SLOW_METRICS_FUEL_LEVEL_PC_NAME "fuel_level_pc"
#define BINOCAN_BASE_SLOW_METRICS_LV_VOLTAGE_V_NAME "lv_voltage_v"
#define BINOCAN_BASE_FAST_METRICS_RPM_NAME "rpm"
#define BINOCAN_BASE_FAST_METRICS_SPEED_KPH_NAME "speed_kph"

/**
 * Signals in message extra_chargecooling_metrics.
 *
 * Metrics related to chargecooling
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_extra_chargecooling_metrics_t {
    /**
     * Bitmask used to highlight unavailable signals in a standard message
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bitmask;

    /**
     * Charge coolant temperature at intercooler inlet
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charge_coolant_temp_in;

    /**
     * Charge coolant temperature out of the intake intercooler
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charge_coolant_temp_out;
};

/**
 * Signals in message base_active_hi_lo.
 *
 * Medium priority cyclic and trigger telltale message
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_base_active_hi_lo_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ignition_ah_st;

    /**
     * High beams telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hi_beams_ah_tt;

    /**
     * Battery or alternator telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t alternator_al_tt;

    /**
     * Low brake fluid telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_low_al_tt;

    /**
     * Parking brake telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t parking_brake_al_tt;

    /**
     * Low oil pressure telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t oil_pressure_al_tt;

    /**
     * Airbag telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t airbag_al_tt;

    /**
     * Check Engine Light telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cel_al_tt;

    /**
     * Turn indicators telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t right_turn_ah_tt;

    /**
     * Turn indicators telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t left_turn_ah_tt;

    /**
     * ABS telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t abs_al_tt;

    /**
     * Door telltale status
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t door_al_tt;

    /**
     * Low coolant level telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t coolant_low_al_tt;

    /**
     * Button status
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t button_al;

    /**
     * Unknown active high. Could be alarm or revlight
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b07_ah;

    /**
     * LCD backlight input, might be related to headlights in low beam or position.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t backlight_ah;

    /**
     * Coolant overtemperature telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t over_temperature_tt;

    /**
     * Low fuel level telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fuel_low_tt;
};

/**
 * Signals in message extra_oil_metrics.
 *
 * Message for extra measurements related to oil metrics
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_extra_oil_metrics_t {
    /**
     * Bitmask used to highlight unavailable signals in a standard message
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bitmask;

    /**
     * Optional oil pressure reading
     *
     * Range: 0..255 (0..25.5 bar)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t oil_pressure;

    /**
     * Optional oil temperature reading
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t oil_temperature;
};

/**
 * Signals in message base_slow_metrics.
 *
 * Slow cyclic message with numerical readings
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_base_slow_metrics_t {
    /**
     * Indicated coolant temperature
     *
     * Range: 0..255 (70..172 degC)
     * Scale: 0.4
     * Offset: 70
     */
    uint8_t coolant_temp;

    /**
     * Relative fuel tank level
     *
     * Range: 0..255 (0..127.5 pc)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t fuel_level_pc;

    /**
     * 12V measured after protection circuitry
     *
     * Range: 0..255 (0..25.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t lv_voltage_v;
};

/**
 * Signals in message base_fast_metrics.
 *
 * Fast cyclic message for base vehicle metrics and telltale triggers
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_base_fast_metrics_t {
    /**
     * Engine rotations in RPM
     *
     * Range: 0..65535 (0..9174.9 -)
     * Scale: 0.14
     * Offset: 0
     */
    uint16_t rpm;

    /**
     * Vehicle speed in km/h
     *
     * Range: 0..65535 (0..2621.4 kph)
     * Scale: 0.04
     * Offset: 0
     */
    uint16_t speed_kph;
};

/**
 * Pack message extra_chargecooling_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_extra_chargecooling_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_extra_chargecooling_metrics_t *src_p,
    size_t size);

/**
 * Unpack message extra_chargecooling_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_extra_chargecooling_metrics_unpack(
    struct binocan_extra_chargecooling_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from extra_chargecooling_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_extra_chargecooling_metrics_init(struct binocan_extra_chargecooling_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_chargecooling_metrics_bitmask_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_chargecooling_metrics_bitmask_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_chargecooling_metrics_bitmask_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_chargecooling_metrics_charge_coolant_temp_in_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_chargecooling_metrics_charge_coolant_temp_in_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_chargecooling_metrics_charge_coolant_temp_in_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_chargecooling_metrics_charge_coolant_temp_out_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_chargecooling_metrics_charge_coolant_temp_out_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_chargecooling_metrics_charge_coolant_temp_out_is_in_range(uint8_t value);

/**
 * Pack message base_active_hi_lo.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_base_active_hi_lo_pack(
    uint8_t *dst_p,
    const struct binocan_base_active_hi_lo_t *src_p,
    size_t size);

/**
 * Unpack message base_active_hi_lo.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_base_active_hi_lo_unpack(
    struct binocan_base_active_hi_lo_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from base_active_hi_lo.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_base_active_hi_lo_init(struct binocan_base_active_hi_lo_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_ignition_ah_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_ignition_ah_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_ignition_ah_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_hi_beams_ah_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_hi_beams_ah_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_hi_beams_ah_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_alternator_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_alternator_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_alternator_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_brake_low_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_brake_low_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_brake_low_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_parking_brake_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_parking_brake_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_parking_brake_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_oil_pressure_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_oil_pressure_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_oil_pressure_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_airbag_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_airbag_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_airbag_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_cel_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_cel_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_cel_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_right_turn_ah_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_right_turn_ah_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_right_turn_ah_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_left_turn_ah_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_left_turn_ah_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_left_turn_ah_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_abs_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_abs_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_abs_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_door_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_door_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_door_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_coolant_low_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_coolant_low_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_coolant_low_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_button_al_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_button_al_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_button_al_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_b07_ah_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_b07_ah_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_b07_ah_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_backlight_ah_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_backlight_ah_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_backlight_ah_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_over_temperature_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_over_temperature_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_over_temperature_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_active_hi_lo_fuel_low_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_active_hi_lo_fuel_low_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_active_hi_lo_fuel_low_tt_is_in_range(uint8_t value);

/**
 * Pack message extra_oil_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_extra_oil_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_extra_oil_metrics_t *src_p,
    size_t size);

/**
 * Unpack message extra_oil_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_extra_oil_metrics_unpack(
    struct binocan_extra_oil_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from extra_oil_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_extra_oil_metrics_init(struct binocan_extra_oil_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_oil_metrics_bitmask_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_oil_metrics_bitmask_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_oil_metrics_bitmask_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_oil_metrics_oil_pressure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_oil_metrics_oil_pressure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_oil_metrics_oil_pressure_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_oil_metrics_oil_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_oil_metrics_oil_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_oil_metrics_oil_temperature_is_in_range(uint8_t value);

/**
 * Pack message base_slow_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_base_slow_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_base_slow_metrics_t *src_p,
    size_t size);

/**
 * Unpack message base_slow_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_base_slow_metrics_unpack(
    struct binocan_base_slow_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from base_slow_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_base_slow_metrics_init(struct binocan_base_slow_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_slow_metrics_coolant_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_slow_metrics_coolant_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_slow_metrics_coolant_temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_slow_metrics_fuel_level_pc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_slow_metrics_fuel_level_pc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_slow_metrics_fuel_level_pc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_slow_metrics_lv_voltage_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_slow_metrics_lv_voltage_v_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_slow_metrics_lv_voltage_v_is_in_range(uint8_t value);

/**
 * Pack message base_fast_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_base_fast_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_base_fast_metrics_t *src_p,
    size_t size);

/**
 * Unpack message base_fast_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_base_fast_metrics_unpack(
    struct binocan_base_fast_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from base_fast_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_base_fast_metrics_init(struct binocan_base_fast_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t binocan_base_fast_metrics_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_fast_metrics_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_fast_metrics_rpm_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t binocan_base_fast_metrics_speed_kph_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_fast_metrics_speed_kph_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_fast_metrics_speed_kph_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
