/**
 * @file binocan.h
 *
 * @brief This header file was generated by cantools version 40.2.1 Thu Jul 17 13:46:18 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BINOCAN_H
#define BINOCAN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_FRAME_ID (0x201u)
#define BINOCAN_BASE_TELLTALES_FRAME_ID (0x101u)
#define BINOCAN_EXTRA_OIL_METRICS_FRAME_ID (0x200u)
#define BINOCAN_BASE_SLOW_METRICS_FRAME_ID (0x110u)
#define BINOCAN_BASE_VEHICLE_METRICS_FRAME_ID (0x100u)

/* Frame lengths in bytes. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_LENGTH (8u)
#define BINOCAN_BASE_TELLTALES_LENGTH (8u)
#define BINOCAN_EXTRA_OIL_METRICS_LENGTH (8u)
#define BINOCAN_BASE_SLOW_METRICS_LENGTH (8u)
#define BINOCAN_BASE_VEHICLE_METRICS_LENGTH (8u)

/* Extended or standard frame types. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_IS_EXTENDED (0)
#define BINOCAN_BASE_TELLTALES_IS_EXTENDED (0)
#define BINOCAN_EXTRA_OIL_METRICS_IS_EXTENDED (0)
#define BINOCAN_BASE_SLOW_METRICS_IS_EXTENDED (0)
#define BINOCAN_BASE_VEHICLE_METRICS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define BINOCAN_BASE_TELLTALES_ABS_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_ABS_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_AIRBAG_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_AIRBAG_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_CEL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_CEL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_HIGH_BEAMS_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_HIGH_BEAMS_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_LOW_BRAKE_FLUID_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_LOW_BRAKE_FLUID_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_LOW_COOLANT_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_LOW_COOLANT_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_LOW_FUEL_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_LOW_FUEL_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_LOW_OIL_PRESSURE_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_LOW_OIL_PRESSURE_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_LV_SYSTEM_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_LV_SYSTEM_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_OVER_TEMPERATURE_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_OVER_TEMPERATURE_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_PARKING_BRAKE_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_PARKING_BRAKE_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_TELLTALES_TURN_INDICATORS_TT_OFF_CHOICE (0u)
#define BINOCAN_BASE_TELLTALES_TURN_INDICATORS_TT_ON_CHOICE (1u)

#define BINOCAN_BASE_VEHICLE_METRICS_IGNITION_ST_OFF_CHOICE (0u)
#define BINOCAN_BASE_VEHICLE_METRICS_IGNITION_ST_ON_CHOICE (1u)

/* Frame Names. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_NAME "extra_chargecooling_metrics"
#define BINOCAN_BASE_TELLTALES_NAME "base_telltales"
#define BINOCAN_EXTRA_OIL_METRICS_NAME "extra_oil_metrics"
#define BINOCAN_BASE_SLOW_METRICS_NAME "base_slow_metrics"
#define BINOCAN_BASE_VEHICLE_METRICS_NAME "base_vehicle_metrics"

/* Signal Names. */
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_BITMASK_NAME "bitmask"
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_CHARGE_COOLANT_TEMP_IN_NAME "charge_coolant_temp_in"
#define BINOCAN_EXTRA_CHARGECOOLING_METRICS_CHARGE_COOLANT_TEMP_OUT_NAME "charge_coolant_temp_out"
#define BINOCAN_BASE_TELLTALES_ABS_TT_NAME "abs_TT"
#define BINOCAN_BASE_TELLTALES_AIRBAG_TT_NAME "airbag_TT"
#define BINOCAN_BASE_TELLTALES_CEL_TT_NAME "CEL_TT"
#define BINOCAN_BASE_TELLTALES_HIGH_BEAMS_TT_NAME "high_beams_TT"
#define BINOCAN_BASE_TELLTALES_LOW_BRAKE_FLUID_TT_NAME "low_brake_fluid_TT"
#define BINOCAN_BASE_TELLTALES_LOW_COOLANT_TT_NAME "low_coolant_TT"
#define BINOCAN_BASE_TELLTALES_LOW_FUEL_TT_NAME "low_fuel_TT"
#define BINOCAN_BASE_TELLTALES_LOW_OIL_PRESSURE_TT_NAME "low_oil_pressure_TT"
#define BINOCAN_BASE_TELLTALES_LV_SYSTEM_TT_NAME "lv_system_TT"
#define BINOCAN_BASE_TELLTALES_OVER_TEMPERATURE_TT_NAME "over_temperature_TT"
#define BINOCAN_BASE_TELLTALES_PARKING_BRAKE_TT_NAME "parking_brake_TT"
#define BINOCAN_BASE_TELLTALES_TURN_INDICATORS_TT_NAME "turn_indicators_TT"
#define BINOCAN_EXTRA_OIL_METRICS_BITMASK_NAME "bitmask"
#define BINOCAN_EXTRA_OIL_METRICS_OIL_PRESSURE_NAME "oil_pressure"
#define BINOCAN_EXTRA_OIL_METRICS_OIL_TEMPERATURE_NAME "oil_temperature"
#define BINOCAN_BASE_SLOW_METRICS_COOLANT_TEMP_NAME "coolant_temp"
#define BINOCAN_BASE_SLOW_METRICS_FUEL_LEVEL_NAME "fuel_level"
#define BINOCAN_BASE_SLOW_METRICS_LV_VOLTAGE_NAME "lv_voltage"
#define BINOCAN_BASE_VEHICLE_METRICS_RPM_NAME "rpm"
#define BINOCAN_BASE_VEHICLE_METRICS_SPEED_NAME "speed"
#define BINOCAN_BASE_VEHICLE_METRICS_IGNITION_ST_NAME "ignition_ST"

/**
 * Signals in message extra_chargecooling_metrics.
 *
 * Metrics related to chargecooling
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_extra_chargecooling_metrics_t {
    /**
     * Bitmask used to highlight unavailable signals in a standard message
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bitmask;

    /**
     * Charge coolant temperature at intercooler inlet
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charge_coolant_temp_in;

    /**
     * Charge coolant temperature out of the intake intercooler
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charge_coolant_temp_out;
};

/**
 * Signals in message base_telltales.
 *
 * Medium priority cyclic and trigger telltale message
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_base_telltales_t {
    /**
     * ABS telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t abs_tt;

    /**
     * Airbag telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t airbag_tt;

    /**
     * Check Engine Light telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cel_tt;

    /**
     * High beams telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t high_beams_tt;

    /**
     * Low brake fluid telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t low_brake_fluid_tt;

    /**
     * Low coolant level telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t low_coolant_tt;

    /**
     * Low fuel level telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t low_fuel_tt;

    /**
     * Low oil pressure telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t low_oil_pressure_tt;

    /**
     * Battery or alternator telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t lv_system_tt;

    /**
     * Coolant overtemperature telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t over_temperature_tt;

    /**
     * Parking brake telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t parking_brake_tt;

    /**
     * Turn indicators telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t turn_indicators_tt;
};

/**
 * Signals in message extra_oil_metrics.
 *
 * Message for extra measurements related to oil metrics
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_extra_oil_metrics_t {
    /**
     * Bitmask used to highlight unavailable signals in a standard message
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bitmask;

    /**
     * Optional oil pressure reading
     *
     * Range: 0..255 (0..25.5 bar)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t oil_pressure;

    /**
     * Optional oil temperature reading
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t oil_temperature;
};

/**
 * Signals in message base_slow_metrics.
 *
 * Slow cyclic message with numerical readings
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_base_slow_metrics_t {
    /**
     * Indicated coolant temperature
     *
     * Range: 0..255 (70..172 degC)
     * Scale: 0.4
     * Offset: 70
     */
    uint8_t coolant_temp;

    /**
     * Relative fuel tank level
     *
     * Range: 0..255 (0..127.5 pc)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t fuel_level;

    /**
     * 12V measured after protection circuitry
     *
     * Range: 0..255 (0..25.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t lv_voltage;
};

/**
 * Signals in message base_vehicle_metrics.
 *
 * Fast cyclic message for base vehicle metrics and telltale triggers
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_base_vehicle_metrics_t {
    /**
     * Engine rotations in RPM
     *
     * Range: 0..65535 (0..9174.9 -)
     * Scale: 0.14
     * Offset: 0
     */
    uint16_t rpm;

    /**
     * Vehicle speed in km/h
     *
     * Range: 0..65535 (0..2621.4 kph)
     * Scale: 0.04
     * Offset: 0
     */
    uint16_t speed;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ignition_st;
};

/**
 * Pack message extra_chargecooling_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_extra_chargecooling_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_extra_chargecooling_metrics_t *src_p,
    size_t size);

/**
 * Unpack message extra_chargecooling_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_extra_chargecooling_metrics_unpack(
    struct binocan_extra_chargecooling_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from extra_chargecooling_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_extra_chargecooling_metrics_init(struct binocan_extra_chargecooling_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_chargecooling_metrics_bitmask_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_chargecooling_metrics_bitmask_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_chargecooling_metrics_bitmask_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_chargecooling_metrics_charge_coolant_temp_in_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_chargecooling_metrics_charge_coolant_temp_in_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_chargecooling_metrics_charge_coolant_temp_in_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_chargecooling_metrics_charge_coolant_temp_out_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_chargecooling_metrics_charge_coolant_temp_out_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_chargecooling_metrics_charge_coolant_temp_out_is_in_range(uint8_t value);

/**
 * Pack message base_telltales.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_base_telltales_pack(
    uint8_t *dst_p,
    const struct binocan_base_telltales_t *src_p,
    size_t size);

/**
 * Unpack message base_telltales.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_base_telltales_unpack(
    struct binocan_base_telltales_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from base_telltales.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_base_telltales_init(struct binocan_base_telltales_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_abs_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_abs_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_abs_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_airbag_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_airbag_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_airbag_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_cel_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_cel_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_cel_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_high_beams_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_high_beams_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_high_beams_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_low_brake_fluid_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_low_brake_fluid_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_low_brake_fluid_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_low_coolant_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_low_coolant_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_low_coolant_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_low_fuel_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_low_fuel_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_low_fuel_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_low_oil_pressure_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_low_oil_pressure_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_low_oil_pressure_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_lv_system_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_lv_system_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_lv_system_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_over_temperature_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_over_temperature_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_over_temperature_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_parking_brake_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_parking_brake_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_parking_brake_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_telltales_turn_indicators_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_telltales_turn_indicators_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_telltales_turn_indicators_tt_is_in_range(uint8_t value);

/**
 * Pack message extra_oil_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_extra_oil_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_extra_oil_metrics_t *src_p,
    size_t size);

/**
 * Unpack message extra_oil_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_extra_oil_metrics_unpack(
    struct binocan_extra_oil_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from extra_oil_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_extra_oil_metrics_init(struct binocan_extra_oil_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_oil_metrics_bitmask_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_oil_metrics_bitmask_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_oil_metrics_bitmask_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_oil_metrics_oil_pressure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_oil_metrics_oil_pressure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_oil_metrics_oil_pressure_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_extra_oil_metrics_oil_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_extra_oil_metrics_oil_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_extra_oil_metrics_oil_temperature_is_in_range(uint8_t value);

/**
 * Pack message base_slow_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_base_slow_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_base_slow_metrics_t *src_p,
    size_t size);

/**
 * Unpack message base_slow_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_base_slow_metrics_unpack(
    struct binocan_base_slow_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from base_slow_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_base_slow_metrics_init(struct binocan_base_slow_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_slow_metrics_coolant_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_slow_metrics_coolant_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_slow_metrics_coolant_temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_slow_metrics_fuel_level_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_slow_metrics_fuel_level_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_slow_metrics_fuel_level_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_slow_metrics_lv_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_slow_metrics_lv_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_slow_metrics_lv_voltage_is_in_range(uint8_t value);

/**
 * Pack message base_vehicle_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_base_vehicle_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_base_vehicle_metrics_t *src_p,
    size_t size);

/**
 * Unpack message base_vehicle_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_base_vehicle_metrics_unpack(
    struct binocan_base_vehicle_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from base_vehicle_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_base_vehicle_metrics_init(struct binocan_base_vehicle_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t binocan_base_vehicle_metrics_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_vehicle_metrics_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_vehicle_metrics_rpm_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t binocan_base_vehicle_metrics_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_vehicle_metrics_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_vehicle_metrics_speed_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_base_vehicle_metrics_ignition_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_base_vehicle_metrics_ignition_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_base_vehicle_metrics_ignition_st_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
